<a id="top"></a>
<span><h1 style="font-family:verdana;"><center><img src="https://numpy.org/images/logo.svg" alt="Flowers in Chania" width=50>NumPy</center></h1></span>
<p><center style="color:#159364; font-family:cursive;">The fundamental package for scientific computing with Python</center></p>

***



<h2><center>Installation of NumPy</center></h2>

<h3>Requirements:</h3>
<p>1. You need to install Python and Pip in your system</p>
<p>2. Open your cmd and run <code>pip install numpy</code></p>


<h2><center>Importing NumPy</center></h2>

In [40]:
#Importing Library
import numpy

array = numpy.array([1, 2, 3, 4, 5])

print(array)

[1 2 3 4 5]


<h2><center>NumPy as np</center></h2>

<p>1. You can also use alias instead of writing complete complete word <b>NumPy</b> again and again</p>
<p>2. While importing you will write <code>import numpy as np</code></p>
<p>3. Now, you can use np </p>


In [41]:
#Importing Library with alias
import numpy as np

array = np.array([1, 2, 3, 4, 5])

print(array)

[1 2 3 4 5]


<h2><center>Accessing Array Element</center></h2>

In [42]:
#Importing Library with alias
import numpy as np

array = np.array([10,20,30,40,50])

print(array[0])

10


In [43]:
array[3]

40

In [44]:
array[1]

20

In [45]:
# array slicing

print(array[0:3])

[10 20 30]


In [46]:
# If we will not provide upper bound, it will consider till last elelemt in the array
print(array[1:])

[20 30 40 50]


In [47]:
# If we will not provide lower bound, it will start from first element of array
print(array[:3])

[10 20 30]


<h2><center>Access 2-D Arrays</center></h2>

In [48]:
import numpy as np

array = np.array([[10,20,30,40,50], [60,70,80,90,100]])

print(array)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [49]:
print(array[0])

[10 20 30 40 50]


In [50]:
print(array[1])

[ 60  70  80  90 100]


In [51]:
print("Printing 2nd element from First Array : ", array[0][1])

Printing 2nd element from First Array :  20


In [52]:
print("Printing 4th element from Second Array : ", array[1][3])

Printing 4th element from Second Array :  90


In [53]:
# If you will exceed the index value it will give you error
print(array[2])

IndexError: index 2 is out of bounds for axis 0 with size 2